### ISSUE TITLE
Modelbuilder_example.ipynb, landboundary create, does not include the Afsluitdijk

### ISSUE THREAD

**Issue by Felix-Deltares** [Deltares/dfm_tools#1041]
The function to create a landboundary ion step 3 of the example notebook, does create a landboundary for the Netherlands, that does not include the "Afsluitdijk". The resulting model of the Wadden Sea is therefor not representative for the real system . Therefor is is a major objection to use the modelbuilder, which is a pity.

Function that creates the landboundary:   dfmt.generate_bndpli_cutland
That automatically is pointed to download gshhg-shp-2.3.7.zip from [www.ngdc.noaa.gov](https://www.ngdc.noaa.gov/)

**Comment by veenstrajelmer** [comment]
@Felix-Deltares the function `dfmt.generate_bndpli_cutland` is meant to use for larger scale models and is mostly useful for demonstration purposes and to fill in a step that was previously missing in the modelbuilder workflows. However, if one wants to achieve very specific results, a bit more coding is required indeed. In this case you would have to define yourself the locations of the model boundary polyline.

Furthermore, many of the other modelbuilder functions can still be used to generate the model you want, despite of this "shortcoming".
