### ISSUE TITLE
Incorrect plotting of coordinates in vertical slices in latest versions of Delft3D FM

### ISSUE THREAD

**Issue by SCLaan** [Deltares/dfm_tools#367]
When taking a vertical slice from model output with Delft3D FM 2023.02 I noticed that there is data being plotted above the waterlevel. This seems to be a copy of the data in the bottom layer. I set up a minimal example here:
P:\11208983-epd-support-tools\training\mapslice_bug\mapslice_bug.py

This problem didn't occur with older versions of Delft3D.

older version:
![mapslice_older_version](https://github.com/Deltares/dfm_tools/assets/58480503/42c88bcf-de95-44fe-af88-4b3841501dd0)

2023.02 version:
![mapslice_202302_version](https://github.com/Deltares/dfm_tools/assets/58480503/4f7751cc-f8fa-4b85-8a5a-277391e43e49)

2023.02 version (no fixed ylim):
![mapslice_202302_version_freeylim](https://github.com/Deltares/dfm_tools/assets/58480503/4be1b4b2-d301-4e3c-8aa6-1a56475d235b)

**Comment by veenstrajelmer** [comment]
MWE:
```
import datetime as dt
import matplotlib.pyplot as plt
#plt.close('all')
import hydrolib.core.dflowfm as hcdfm
import dfm_tools as dfmt

# works with old map output:
map_netcdf = r'p:\11208983-epd-support-tools\training\short_simulation\copy_of_netcdfs\HK-FMWAQ_0007_map.nc'
# but not with 2023.02:
map_netcdf = r'p:\11208983-epd-support-tools\training\HK-DFM_Day2_Hydrodynamics\Exercises\Post-processing\HK-DFM_model_with_output\DFM_OUTPUT_HK-FMWAQ\HK-FMWAQ_0019_map.nc'

# use xarray to open the map netcdf
map_xr = dfmt.open_partitioned_dataset(map_netcdf)
map_xr = map_xr.ugrid.sel(x=slice(114.198,114.23))

# load polyline of cross-section in Victoria Harbour
file_pli    = r'p:\11208983-epd-support-tools\training\HK-DFM_Day2_Hydrodynamics\Exercises\Post-processing\VictoriaHarbour.pli'
pli_object  = hcdfm.PolyFile(file_pli)
polyline_pd = dfmt.pointlike_to_DataFrame(pli_object.objects[0])
polyline_pd_geo = dfmt.pointlike_to_geodataframe(pli_object.objects[0])

# take vertical slice
xr_crs_ugrid = dfmt.polyline_mapslice(map_xr.sel(time=dt.datetime(2014,3,19),method='nearest'), polyline_pd)

# plot salinity in slice
fig, ax = plt.subplots()
xr_crs_ugrid['mesh2d_sa1'].ugrid.plot(cmap='jet',vmin=32.6,vmax=33.1)
ax.set_ylim([-40,100])
fig.tight_layout()
```

**Comment by veenstrajelmer** [comment]
The sigma interface percentage in the new modelrun contains a nan (which should not be there but is also not correctly parsed to nan by xarray).

Old is DIMRset 2.10.04 from 20-Dec-2019 (OSS 65694):
```
<xarray.DataArray 'mesh2d_interface_sigma' (mesh2d_nInterfaces: 21)>
array([-1.00000000e+00, -9.50000000e-01, -9.00000000e-01, -8.50000000e-01,
       -8.00000000e-01, -7.50000000e-01, -7.00000000e-01, -6.50000000e-01,
       -6.00000000e-01, -5.50000000e-01, -5.00000000e-01, -4.50000000e-01,
       -4.00000000e-01, -3.50000000e-01, -3.00000000e-01, -2.50000000e-01,
       -2.00000000e-01, -1.50000000e-01, -1.00000000e-01, -5.00000000e-02,
        2.22044605e-16])
```

New is DIMRset 2.22.15 from 27-1-2023 (OSS 142431, 2023.02 unsigned):
```
<xarray.DataArray 'mesh2d_interface_sigma' (mesh2d_nInterfaces: 21)>
array([ 9.96920997e+36, -9.50000000e-01, -9.00000000e-01, -8.50000000e-01,
       -8.00000000e-01, -7.50000000e-01, -7.00000000e-01, -6.50000000e-01,
       -6.00000000e-01, -5.50000000e-01, -5.00000000e-01, -4.50000000e-01,
       -4.00000000e-01, -3.50000000e-01, -3.00000000e-01, -2.50000000e-01,
       -2.00000000e-01, -1.50000000e-01, -1.00000000e-01, -5.00000000e-02,
        2.22044605e-16])
```

A quick workaround is replacing it by -100, a nan would remove the bottom layer which does not make sense in case of sigma layers:
```
import netCDF4
fillvals = netCDF4.default_fillvals
sigma_int_percts = map_xr['mesh2d_interface_sigma']
if fillvals['f8'] in sigma_int_percts:
    sigma_int_percts[sigma_int_percts==fillvals['f8']] = -100
    map_xr['mesh2d_interface_sigma'][:] = sigma_int_percts
```

Could you check if there is an UNST issue available for this issue?

**Comment by SCLaan** [comment]
Hi Jelmer! Thanks! This is a good short-term solution.

I started a short simulation with the latest DIMR version:
p:\11208983-epd-support-tools\training\short_simulation\S01x_8core_dfm_tools_issue_367\

I did a quick scan of JIRA, but couldn't find any related issues. Let's see what this new simulation does and inform Tjitske if this problem persists.

**Comment by veenstrajelmer** [comment]
Repaired in DIMRset 2.26.01
