### ISSUE TITLE
Improve writing astro .bc file (format, FES2014 constituents+order) 

### ISSUE THREAD

**Issue by JulienGroenenboom** [Deltares/dfm_tools#414]
To extend and align it with the default used in the MATLAB version (for easier comparison). Compare:
p:\11209231-003-bes-modellering\hydrodynamica\preprocessing\FES_MATLAB_vs_python\MATLAB\bc\bovenwindse_eilanden_bnd.bc
p:\11209231-003-bes-modellering\hydrodynamica\preprocessing\FES_MATLAB_vs_python\python\modelbuilder_input_bovenwindse_eilanden.py

**Comment by veenstrajelmer** [comment]
You can provide a `component_list` argument to the `interpolate_tide_to_bc` function:
https://github.com/Deltares/dfm_tools/blob/1b8d68bb050edffdaca4a7bc261664c975285fb9/dfm_tools/interpolate_grid2bnd.py#L79C49-L79C63
The order of the components in `component_list` should be the order in the bc file.

**Comment by veenstrajelmer** [comment]
This issue came from hardcoding in modelbuilder.py, so an alternative solution is to update the modelbuilder example script with a tide part and remove that from modelbuilder.py:

```
import os
import dfm_tools as dfmt
import hydrolib.core.dflowfm as hcdfm

ext_bnd = ''
file_pli = ''
dir_output='.'

file_bc_basename = os.path.basename(file_pli).replace('.pli','')
ForcingModel_object = dfmt.interpolate_tide_to_bc(tidemodel='FES2014', file_pli=file_pli, component_list=None, nPoints=None)
file_bc_out = os.path.join(dir_output,f'tide_{file_bc_basename}_FES2014.bc')
ForcingModel_object.save(filepath=file_bc_out)

#generate boundary object for the ext file (quantity, pli-filename, bc-filename)
boundary_object = hcdfm.Boundary(quantity='waterlevelbnd', #the FM quantity for tide is also waterlevelbnd
                                 locationfile=file_pli,
                                 forcingfile=ForcingModel_object)
ext_bnd.boundary.append(boundary_object)
```
