### ISSUE TITLE
Correct flowelem_zcc bottom z-layer for z-sigma coordinates from reconstruction

### ISSUE THREAD

**Issue by mgeraeds** [Deltares/dfm_tools#417]
In the reconstruction of mesh2d_flowelem_zcc, the layers are clipped to the bed level. Thus, the bottom z-layer of the mesh2d_flowelem_zcc coordinate is set equal to the bed level. This not correct, because the location of the mesh2d_flowelem_zcc should be halfway the bottom vertical grid cell. Also, with FullGridOutput on, the rest of the values below the clipped bed level are normally set to NaN, and that is not the case when reconstructing the mesh2d_flowelem_zcc and mesh2d_flowelem_zw quantities with the reconstruct_zw_zcc_fromzsigma function.

Requirements:
- [x] #746
- [x] derive zcc as midpoints between interfaces, this way the bottom zcc is not clipped to the bedlevel. This is not relevant for sigma layers. For z-models it is relevant for both the bedlevel and waterlevel, for z-sigma only for the bedlevel. >> https://github.com/Deltares/dfm_tools/issues/754
- [x] z-values (zcc/zw) below bottom should prefferably be nan and not clipped to the bedlevel. >> https://github.com/Deltares/dfm_tools/issues/754
- [x] #758
- [ ] with the above points, keepzlayeringatbed=0 is succesful. Also consider implementing 1 (merge lower layers) and 2 (put interface between bottom layers in the middle), does this require thresholds?

zw is layer interfaces
zcc is layer centers

**Comment by veenstrajelmer** [comment]
zw is layer interfaces
zcc is layer centers

More requirements:
- derive zcc as midpoints between interfaces, this way the bottom zcc is not clipped to the bottom
- z-values (zcc/zw) below bottom should be nan and not clipped to the bottom
- with the above points, keepzlayeringatbed=0 is succesful. Also consider implementing 1 (merge lower layers) and 2 (put interface between bottom layers in the middle)

**Comment by veenstrajelmer** [comment]
Most of the sub-issues were taken care of. The layer reconstruction now correctly derives z-values for `keeplayeringatbed=0`. In the future, maybe consider implementing `keeplayeringatbed=1` (merge lower layers) and `keeplayeringatbed=2` (put interface between bottom layers in the middle). This might require thresholds?
