### ISSUE TITLE
Adding quiverkey-like labeled arrow lengths to curly vectors

### ISSUE THREAD

**Issue by shenyulu** [Deltares/dfm_tools#483]
[[#matplotlib/](https://github.com/matplotlib/matplotlib/issues/20038)](https://github.com/matplotlib/matplotlib/issues/20038#issuecomment-1491233325) and `dfm_tools/modplot.py` is a wonderful answer about solving curly vectors plotting, but I'm having a difficulty whether I can add a plot scale key similar to QuiverKey. Maybe it can be achieved in a simple way. Thank you very much for your preliminary work.

**Comment by veenstrajelmer** [comment]
I think this is because the `magnitude` value is automatically derived internally. Maybe a solution would be to add a `scale` argument to multiply with `magnitude`, but I am not sure if it would work. Could you test it?

**Comment by veenstrajelmer** [comment]
Closed due to inactivity.
