### ISSUE TITLE
update meshkernel api calls after new release

### ISSUE THREAD

**Issue by veenstrajelmer** [Deltares/dfm_tools#563]
- [x] the new meshkernelpy release will contain changes in API calls, update these. See below comments from Ahmad for details.
- [x] update minimal meshkernel version
- [x] renaming of `is_geographic` to `projection` in dfm_tools, hydrolib-core, xugrid, hydromt_delft3dfm >> including enforced ProjectionType
- [x] update/try testbank (`test_meshkernel_helpers.py`), modelbuilder notebook, modelbuilder example script, creategrid example script, maybe more
- [x] revert git link for hydrolib-core in pyproject.toml and requirements.txt

PRs:
- hydromt_delft3dfm: https://github.com/Deltares/hydromt_delft3dfm/pull/109 >> success
- hydrolib-core: https://github.com/Deltares/HYDROLIB-core/pull/574 >> success
- xugrid: https://github.com/Deltares/xugrid/pull/171 >> success
- dfm_tools: https://github.com/Deltares/dfm_tools/pull/621 >> success

**Comment by ahmad-el-sayed** [comment]
The following methods have been renamed:

- `mesh2d_make_mesh_from_polygon` -> `mesh2d_make_triangular_mesh_from_polygon`
- `mesh2d_make_mesh_from_samples` -> `mesh2d_make_triangular_mesh_from_samples`
- `curvilinear_make_uniform`  -> `curvilinear_compute_rectangular_grid`
- `curvilinear_make_uniform_from_polygon` -> `curvilinear_compute_rectangular_grid_from_polygon`
- `curvilinear_make_uniform_on_extension` -> `curvilinear_compute_rectangular_grid_on_extension`

New methods:

- mesh2d_make_rectangular_mesh
- mesh2d_make_rectangular_mesh_from_polygon
- mesh2d_make_rectangular_mesh_on_extension

Similar to mesh2d_make_triangular_mesh_*,  the new functions do not require calling curvilinear_convert_to_mesh2d() after using curvilinear_make_rectangular_grid_*.

**Comment by ahmad-el-sayed** [comment]
**Specification of projection**

The constructor MeshKernel is no longer parametrised by an optional boolean (used to be false for Cartesian coordinates, which is the default, and true for spherical). Now it takes an optional enum, ProjectionType, which is can be CARTESIAN, SPHERICAL or SPHERICALACCURATE. Only the first 2 are supported. The 3rd should result in an exception.

**Comment by ahmad-el-sayed** [comment]
Mesh deletion enumerator: to do

**Comment by ahmad-el-sayed** [comment]
Adapt mesh2d_connect_meshes signature: `def mesh2d_connect_meshes(self, mesh2d: Mesh2d, search_fraction: float) -> None`. Recommended `search_fraction = 0.4` (was the hardcoded default in the back-end).

**Comment by ahmad-el-sayed** [comment]
New method: `mesh2d_merge_nodes_with_merging_distance`
