### ISSUE TITLE
While writing .bc file (based on CMEMS-data): skip support points containing NaN's

### ISSUE THREAD

**Issue by Julien-Groenenboom** [Deltares/dfm_tools#627]
At the moment, my .bc contains a lot of 0's as according to the info message "Nan values replaced with 0 to avoid bc-writing errors".

Suggestion: Don't write this data to e.g. support_point_0001 (NaN's) and start with support_point_0002 (reasonable data). Delft3D FM will subsequently do the extrapolation to support_point_0001.

**Comment by veenstrajelmer** [comment]
https://github.com/Deltares/dfm_tools/issues/628
