### ISSUE TITLE
`remove_edges` gives unexpected behaviour for enriched rst file

### ISSUE THREAD

**Issue by veenstrajelmer** [Deltares/dfm_tools#680]
When enriching rst with map, for some reason the `remove_unassociated_edges` function causes what it should prevent: `"ValueError: connectivity contains negative values"`. When passing `remove_edges=False` the file can be read successfully, but there is probably some bug here.

```
import dfm_tools as dfmt
file_nc_rst = r'p:\11209231-001-dwsm-slib2023\02_Modelling\04_Mud\Mud_v2_20162017_rst2\DFM_OUTPUT_DWSM-FM_200m\DWSM-FM_200m_0000_20161222_000000_rst.nc'
uds_rst = dfmt.open_partitioned_dataset(file_nc_rst, preprocess=dfmt.enrich_rst_with_map)#, remove_edges=False)
uds_rst.taus.isel(time=-1).ugrid.plot()
```

**Comment by SCLaan** [comment]
I encountered the same problem with merged map files. However, using `remove_edges=False` did not solve this problem. See:
```
import dfm_tools as dfmt
merged_file = r'p:\11208983-epd-support-tools\toolbox\EPD_Support_Tool\simulations\HK-DFM_scenario\merged\HK-FMWAQ_merged_map.nc'
data_xr = dfmt.open_partitioned_dataset(merged_file,remove_edges=False)
```

**Comment by veenstrajelmer** [comment]
The error is caused by a bug in xugrid, which will be picked up under this issue: https://github.com/Deltares/xugrid/issues/208
