### ISSUE TITLE
ImportError: cannot import name 'get_ncmodeldata' from 'dfm_tools.get_nc' 

### ISSUE THREAD

**Issue by nyanyaleam** [Deltares/dfm_tools#687]
cant import

**Comment by veenstrajelmer** [comment]
This function is deprecated and does not exist anymore. The fact that you run into this error means you are probably using an old script. Please have a look at the [example post-processing notebook](https://github.com/Deltares/dfm_tools/blob/main/docs/notebooks/postprocessing_example.ipynb) for the updated method for reading D-FlowFM or other ugrid data. Could you let me know if this helps?
