### ISSUE TITLE
merge circumcenters option?

### ISSUE THREAD

**Issue by thopri** [Deltares/dfm_tools#812]
Hello,

I am using dfm_tools and adapting the model builder example to create a model configuration, this all works well unless the coastline is quite complicated, e.g. French coast on the English Channel. When trying to run the configuration I get the following error:

ERROR  :   748 small flow links discarded. Run 'merge circumcenters' to remove small flow links or increase threshold

The merge circumcenters doesn't seem to be part of dfm_tools? I can only find references for the option in the delft3d GUI. The only solution I have found so far is to increase the cell size but this often ends with quite a large resolution before all the circumcenters are on longer too close together.

I can see that there is a threshold that can be increased? its not clear where to do this or if it is sensible to do so?

Any guidance would be appreciated.

**Comment by veenstrajelmer** [comment]
@lucacarniato would you have time to provide a meshkernel example for merge circumcenters?

**Comment by thopri** [comment]
Would the function "mkernel_mesh2d_delete_small_flow_edges_and_small_triangles";on this page 

https://deltares.github.io/MeshKernel/namespacemeshkernelapi.html#a40a8202bcfaa2902b5d42aed1cec50bb

Be a solution?

**Comment by thopri** [comment]
Or the function "mkernel_mesh2d_merge_nodes"?

**Comment by lucacarniato** [comment]
`mk.mesh2d_delete_small_flow_edges_and_small_triangles` is intended for deleting small flow edges. A representative flow edge length is computed from the square root of the average area of neighboring faces. The 'small_flow_edges_length_threshold' is used as a multiplier of this area for deleting the edges crossed by such small flow edges. 

`min_fractional_area_triangles` is used as a multiplier of the average face area to determine triangles at the boundary which can be deleted.

**Comment by thopri** [comment]
Excellent thanks for the help, my model config now runs 😃

**Comment by veenstrajelmer** [comment]
Hi @thopri, please also check https://github.com/Deltares/dfm_tools/issues/1144, I think your grid could benefit from a different dx/dy aspect ratio. This will result in a better grid then when removing the small flow links.
