### ISSUE TITLE
** ERROR  : network is not orthogonal

### ISSUE THREAD

**Issue by thopri** [Deltares/dfm_tools#825]
Hi,

Thanks for your help previously, I now have a new issue that I could use some guidance for. I am trying a new model domain and I am getting the following error when running dflowfm

** ERROR  : network is not orthogonal

I assume this means my grid needs more refinement but I am not sure if there is a way for dfm_tools to do that? Some pointers would be appreciated.

Many Thanks

**Comment by thopri** [comment]
![Screenshot_20240418_095411](https://github.com/Deltares/dfm_tools/assets/41162894/f6f253f5-9418-4043-9077-b2b5d0b18115)
![Screenshot_20240418_095435](https://github.com/Deltares/dfm_tools/assets/41162894/abec9529-ab7f-4f15-bb47-d1bec342e1d4)
![Screenshot_20240418_095456](https://github.com/Deltares/dfm_tools/assets/41162894/c8cc912a-0618-4e8f-b214-fed896465885)

**Comment by veenstrajelmer** [comment]
Hi @thopri, this is probably because of this issue: https://github.com/Deltares/MeshKernelPy/issues/150

A simple fix would be to use a larger value for `area_min` for `dfmt.meshkernel_delete_withcoastlines()` (the unit is square kilometers). This excludes all small islands to be deleted and it often solves this issue. Does it work for you?

**Comment by thopri** [comment]
Hello! Yes that is the issue, I have applied the mesh2d_get_orthogonality().values.max() method before and after meshkernel_delete_withcoastlines() returning values of 0.00015 before and 0.53695 after. However setting min_area at values from 0.3 to 10km2 has not fixed it. I can't see any holes like in the issue you linked so am slightly stumped. Does 10km2 sound like a reasonable amount? the cell size is between 1/20th degree at the coarse side and 300m at the fine side.

**Comment by thopri** [comment]
I am using the high res coastline, maybe using a lower res option would be helpful? The coastline is quite complicated

**Comment by thopri** [comment]
Ok, increasing the min area parameter doesn't appear to help, if anything it makes the orthogonality worse. (~0.75). Different resolution of coastlines doesn't seem to have much impact. So any more help would be appreciated!

**Comment by thopri** [comment]
Just to update, the model runs fine if I don't clip the coastline. I have been measuring the size of some of the holes in the coastline due to the esturaries/rivers and am increasing the min size to remove them. Currently at 250 km2 and 0.4 orthogonality so I think this will work if I get to a certain level. (currently trying 750km2)

**Comment by veenstrajelmer** [comment]
That is a bit much, but if it works it works.. We are working on this in the issue that I linked, hopefully this will be a bit more charming in the future.

**Comment by thopri** [comment]
Thought I would add some extra experience here, creating a new domain resulted in the same issue, increasing min area didn't help at all. But I found the solution in this case was one I mentioned above, changing the coastline shapefile resolution. The options are f, full, h, high, i, intermediate, l, low and c, coarse. 

I found setting res to "i" resulted in an value low enough for the model to run. "l" was even better but then the coastline was pretty inaccurate. Hope that helps someone (probably me) in the future.

**Comment by veenstrajelmer** [comment]
There will always

**Comment by veenstrajelmer** [comment]
From dfm_tools 0.24.0 (not released yet), there will be a new function called `dfmt.meshkernel_get_illegalcells()` that derives polygons about the 6-edged-cells that cause this high orthogonality. The example notebook already includes how to work with this (including the relevant mdu setting). dfm_tools 0.24.0 was not released yet, but you can try it out after the release is done.
