### ISSUE TITLE
add kwargs to wrapper functions for xarray (and possibly more)

### ISSUE THREAD

**Issue by SCLaan** [Deltares/dfm_tools#865]
I tried to generate boundary conditions based on a set of downloaded netCDFs with CMEMS data. The data was downloaded in multiple batches and the exact domain has changed a little bit over time, either due to the input in the script or possibly adjustments to the buffer zone in dfm_tools. This caused an error:
`ValueError: cannot align objects with join='exact' where index/labels/sizes are not equal along these coordinates (dimensions): 'longitude' ('longitude',)`

I solved this by changing the hard-coded statement in https://github.com/Deltares/dfm_tools/blob/5ca89150156ce0cddd9a8fca1dfba9481a569643/dfm_tools/interpolate_grid2bnd.py#L294 and now use `join='inner'`

This made me think it would be good to
- [ ] **make all xarray wrapper functions (and possibly more) more flexible by accepting kwargs**.

In this case this would come down to kwargs being accepted in https://github.com/Deltares/dfm_tools/blob/5ca89150156ce0cddd9a8fca1dfba9481a569643/dfm_tools/modelbuilder.py#L21 and then in the underlying https://github.com/Deltares/dfm_tools/blob/5ca89150156ce0cddd9a8fca1dfba9481a569643/dfm_tools/interpolate_grid2bnd.py#L257

**Comment by SCLaan** [comment]
Just to document my changes. I had to made some additional changes to interpolate_grid2bnd.py, namely:
```
data_xr = xr.open_mfdataset(file_list_nc, chunks=chunks, join='inner',
                            decode_coords="all", preprocess=drop_duplicates_along_all_dims)
```
where I added the preprocessing function drop_duplicates_along_all_dims to remove errors for duplicate (fill) values:
```
def drop_duplicates_along_all_dims(obj, keep="first"):
    """
    Needed as pre-processing for xr.open_mfdataset() to ignore duplicate empty values in datasets.
    """
    
    deduplicated = obj
    for dim in obj.dims:
        indexes = {dim: ~deduplicated.get_index(dim).duplicated(keep=keep)}
        deduplicated = deduplicated.isel(indexes)
    return deduplicated
```

**Comment by veenstrajelmer** [comment]
`join="exact"` was added deliberately for robustness reasons in https://github.com/Deltares/dfm_tools/issues/574. If you run the testcase added in the linked PR I think it would fail after your changes. Could you let me know?
