### ISSUE TITLE
unable to download ERA5 data using dfmt.download_ERA5

### ISSUE THREAD

**Issue by thopri** [Deltares/dfm_tools#971]
Hello,

The API interface for the ERA5 datasets seems to have changed, it uses a cds-beta in its url and the existing auth token no longer works (despite still being in the online account). I had to do a weird dance with ECMWF and CMEMS ending up with a new auth token which seems to pass authentication but I now get an "dataset dummy not found" error. 

```
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://cds-beta.climate.copernicus.eu/api/retrieve/v1/processes/dummy/execute
```

I think the code at   ```File "/home/thopri/miniforge3/envs/mod_build/lib/python3.11/site-packages/dfm_tools/download.py", line 129, in cds_credentials``` is calling a dummy dataset or call to check the auth and this is no longer valid. I will try commenting it out to see if the actual calls are still correct and update here.

**Comment by veenstrajelmer** [comment]
Yes, indeed the dummy dataset is called here:
https://github.com/Deltares/dfm_tools/blob/f6069def4b6ac4507c1e7a6abb90e686826f80c7/dfm_tools/download.py#L125-L129

I have implemented an exception there, but apparently the cdsapi has been changed so this is not catched anymore. Thanks for reporting this. I think that if you roll back to `cdsapi=0.7.0` it will all work just fine. Let me know if that is the case or not. In the meantime I will work on a fix that supports their new code.

**Comment by thopri** [comment]
commenting out the c.retrieve(dummy) seems to have "fixed" it. I did have to accept license terms to get it to work which seemed to involve making a request on the ERA5 web data form thingy here:

https://cds-beta.climate.copernicus.eu/datasets/reanalysis-era5-single-levels?tab=download

**Comment by veenstrajelmer** [comment]
Yes, I know, it is very inconvenient. It has been reported here, so feel free to comment this there: https://github.com/ecmwf/cdsapi/issues/108

**Comment by thopri** [comment]
Yes I am having to add all this to my documentation/notes as its kinda confusing! I hope it becomes clearer out of beta.

**Comment by veenstrajelmer** [comment]
There is however a message when you supply your apikey to dfm_tools, which points to a useful article:
https://github.com/Deltares/dfm_tools/blob/4ae764263d6476895487042b619ee3c16ab667b1/dfm_tools/download.py#L112-L115
So to https://forum.ecmwf.int/t/3743. Maybe you already found this, but if not it might be helpful to not have to document everything yourself.

**Comment by veenstrajelmer** [comment]
As you might have seen the issue was fixed in the main branch. There is one fix pending (https://github.com/Deltares/dfm_tools/issues/962) before I will make a release, I will do this next week.
